api:
  id: "18950051"  

http:
  host: "0.0.0.0"
  port: "8081"
  
https:
  host: "0.0.0.0"
  port: "8082"
  
customerRequest:
  path: "/customer-registration"
  method: "POST"

orders:
  path: "/placing-order"

request:
  host: "prwss-orders-papi.us-e2.cloudhub.io"
  port: "443"
  
tls:
  type: "JKS"
  path: "KeyStore.jks"
  alias: "mulesoft"
  
anypoint:
  clientid: "1f9dfee0c23243ec88abe77addea708e"
  clientsecret: "53c6EED9C16B49a2b0722CDbBe382FC6"