tls:
  pssword: "![zkbX9B/Wjv2zopfd5KbJyw==]"
  
anypoint:
  clientid: "![SoKIrSPSIjUKghnY77MjAugiKgTWrZMRoKJiOtXvb49sxRN6Td3VhA==]"
  clientsecret: "![hvJGV4dfRyTZLJ83hB8qR5NIw0NH8LFWB1DYdri9MqM0Y7vtbfldZw==]"
